### ISSUE TITLE
White space in markbot

### ISSUE THREAD

**Issue by Sk16ck** [Sk16ck/responsive-banner#1]
@thomasjbradley

I have white space at the bottom of my website when I look at it in Markbot but none in the actual browser. Aside that I'm unsure of how to continue from this point forward with the larger screen sizes, unless it is just position at that point.

<img width="397" alt="Screen Shot 2020-01-06 at 12 52 37 PM" src="https://user-images.githubusercontent.com/42048824/71837108-9fea4180-3083-11ea-8e99-12bf0e83bfed.png">

 Thanks

**Comment by thomasjbradley** [comment]
I think it might be because of the `absolute` class. We don’t want `absolute` on the smaller screen sizes—only the larger ones. Try moving it into a `60em` media query.
